/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AlunosController;
import Controller.auxiliar.FormatacaodeCamposRestritos;
import Controller.auxiliar.JMoneyField;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author 55989
 */
public class AlunosView extends javax.swing.JDialog {
    private final java.awt.Frame parent;
    private final int numeroTela = 1;
    private Point point = new Point();
    private final AlunosController controller;
    private AlunosCadastro telaAlunosCadastro;
    private javax.swing.JComboBox<String> comboServicos = new JComboBox<>();
    private javax.swing.JComboBox<String> comboTurmas = new JComboBox<>();
    private javax.swing.JComboBox<String> comboEstado = new JComboBox<>();
    /**
     * Creates new form Alunos
     * @param parent
     * @param modal
     */
    public AlunosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        telaAlunosCadastro = new AlunosCadastro(parent, false);
        
        this.setarComposicaoTabelas();
        
        controller = new AlunosController(this);
        botaoFecharConf.setBackground(new Color(0,0,0,0));
        jButton1.setBackground(new Color(0,0,0,0));
        botaoConfigAdicionais.setBackground(new Color(0,0,0,0));
        botaobuscar.setBackground(new Color(0,0,0,0));
        botaoFechar.setBackground(new Color(0,0,0,0));
        botaoAdicionar.setBackground(new Color(0,0,0,0));
        botaoRemover.setBackground(new Color(0,0,0,0));
        botaoEditar.setBackground(new Color(0,0,0,0));
        botaoListar.setBackground(new Color(0,0,0,0));
        tabelaAlunos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabelaAlunos.getTableHeader().setOpaque(false);
        tabelaAlunos.getTableHeader().setBackground(new Color(0,0,0));
        tabelaAlunos.getTableHeader().setForeground(new Color(0,0,0));
        tabelaAlunos.setRowHeight(25);
        botaoEndereco.setBackground(new Color(0,0,0,0));
        botaoPais.setBackground(new Color(0,0,0,0));
        botaoAlunos.setBackground(new Color(0,0,0,0));
        botaoPlanos.setBackground(new Color(0,0,0,0));
        
        campoAvisoDataVencimento.setVisible(false);
        botaoConfigAdicionais.setVisible(false);
        painelConfiguracoesAdicionais.setVisible(false);
        campoDataVencimento.setEnabled(false);
        campoDataFimPlano.setEnabled(false);
        this.setInicialBotoes();
        fecharTelaESC();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/rehabi.png")).getImage());
        
        
        comboServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServicosActionPerformed(evt);
            }
            private void comboServicosActionPerformed(ActionEvent evt) {
            int linhaSelecionada = tabelaPlanos.getSelectedRow();
                if(tabelaPlanos.isRowSelected(linhaSelecionada)){
                    try {
                        selecionarTabelas(2); 
                        controller.setarValorContrato();
                    } catch (SQLException ex) {
                        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        
    }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConfiguracoesAdicionais = new javax.swing.JPanel();
        botaoFecharConf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoDataCadastro = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        campoDataPagamento = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        campoDataVencimento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoAvisoDataVencimento = new javax.swing.JTextArea();
        campoDataFimPlano = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        painelAlunos = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        painelPlanos = new javax.swing.JScrollPane();
        tabelaPlanos = new javax.swing.JTable();
        painelPais = new javax.swing.JScrollPane();
        tabelaPais = new javax.swing.JTable();
        painelEnderecos = new javax.swing.JScrollPane();
        tabelaEnderecos = new javax.swing.JTable();
        botaoConfigAdicionais = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoListar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        botaobuscar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();
        comboListar = new javax.swing.JComboBox<>();
        comboTurmasExistentes = new javax.swing.JComboBox<>();
        botaoPlanos = new javax.swing.JButton();
        botaoPais = new javax.swing.JButton();
        botaoEndereco = new javax.swing.JButton();
        botaoAlunos = new javax.swing.JButton();
        planodefundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelConfiguracoesAdicionais.setBackground(new java.awt.Color(116, 174, 159));
        painelConfiguracoesAdicionais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFecharConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/btnFecharPeq.png"))); // NOI18N
        botaoFecharConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharConfActionPerformed(evt);
            }
        });
        painelConfiguracoesAdicionais.add(botaoFecharConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Cadastro");
        painelConfiguracoesAdicionais.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        painelConfiguracoesAdicionais.add(campoDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Último Pagamento");
        painelConfiguracoesAdicionais.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        painelConfiguracoesAdicionais.add(campoDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Vencimento");
        painelConfiguracoesAdicionais.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));
        painelConfiguracoesAdicionais.add(campoDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/btnSet.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelConfiguracoesAdicionais.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, 30));

        campoAvisoDataVencimento.setEditable(false);
        campoAvisoDataVencimento.setColumns(20);
        campoAvisoDataVencimento.setRows(5);
        jScrollPane1.setViewportView(campoAvisoDataVencimento);

        painelConfiguracoesAdicionais.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 330, 70));
        painelConfiguracoesAdicionais.add(campoDataFimPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de Fim do Plano");
        painelConfiguracoesAdicionais.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        getContentPane().add(painelConfiguracoesAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 530, 250));

        tabelaAlunos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Nome", "Turma", "Débito", "Renovação Auto."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAlunos.setFocusable(false);
        tabelaAlunos.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaAlunos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaAlunos.setRowHeight(25);
        tabelaAlunos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAlunos.setShowVerticalLines(false);
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMouseClicked(evt);
            }
        });
        tabelaAlunos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabelaAlunosComponentHidden(evt);
            }
        });
        tabelaAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaAlunosKeyReleased(evt);
            }
        });
        painelAlunos.setViewportView(tabelaAlunos);

        getContentPane().add(painelAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 811, 340));

        tabelaPlanos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaPlanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ChavePlano", "Plano/Período", "Valor Contrato", "Valor Mensal", "Dia Vencimento", "Situacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPlanos.setFocusable(false);
        tabelaPlanos.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaPlanos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaPlanos.setRowHeight(25);
        tabelaPlanos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPlanos.setShowVerticalLines(false);
        tabelaPlanos.getTableHeader().setReorderingAllowed(false);
        tabelaPlanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPlanosMouseClicked(evt);
            }
        });
        tabelaPlanos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabelaPlanosComponentHidden(evt);
            }
        });
        tabelaPlanos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaPlanosKeyReleased(evt);
            }
        });
        painelPlanos.setViewportView(tabelaPlanos);

        getContentPane().add(painelPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 811, 340));

        tabelaPais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pai", "CPF (P)", "Contato (P)", "Mãe", "CPF (M)", "Contato (M)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaPais.setFocusable(false);
        tabelaPais.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaPais.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaPais.setRowHeight(25);
        tabelaPais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPais.setShowVerticalLines(false);
        tabelaPais.getTableHeader().setReorderingAllowed(false);
        tabelaPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPaisMouseClicked(evt);
            }
        });
        tabelaPais.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabelaPaisComponentHidden(evt);
            }
        });
        tabelaPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaPaisKeyReleased(evt);
            }
        });
        painelPais.setViewportView(tabelaPais);

        getContentPane().add(painelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 811, 340));

        tabelaEnderecos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Logradouro", "Nº", "Bairro", "Cidade", "Estado", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaEnderecos.setFocusable(false);
        tabelaEnderecos.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaEnderecos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaEnderecos.setRowHeight(25);
        tabelaEnderecos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaEnderecos.setShowVerticalLines(false);
        tabelaEnderecos.getTableHeader().setReorderingAllowed(false);
        tabelaEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEnderecosMouseClicked(evt);
            }
        });
        tabelaEnderecos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabelaEnderecosComponentHidden(evt);
            }
        });
        tabelaEnderecos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaEnderecosKeyReleased(evt);
            }
        });
        painelEnderecos.setViewportView(tabelaEnderecos);

        getContentPane().add(painelEnderecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 811, 340));

        botaoConfigAdicionais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/btnConfiguracoes.png"))); // NOI18N
        botaoConfigAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfigAdicionaisActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfigAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        botaoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoRemover.png"))); // NOI18N
        botaoRemover.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverremover.png"))); // NOI18N
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 168, 205, 50));

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoEditar.png"))); // NOI18N
        botaoEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoEditarHover.png"))); // NOI18N
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 168, 205, 50));

        botaoListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoListar.png"))); // NOI18N
        botaoListar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverListar.png"))); // NOI18N
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 205, 50));

        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaofechar.png"))); // NOI18N
        botaoFechar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverfechar.png"))); // NOI18N
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 220, 50));

        botaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscar.png"))); // NOI18N
        botaobuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscarHover.png"))); // NOI18N
        botaobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botaobuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 50, 40));

        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoAdicionar.png"))); // NOI18N
        botaoAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverAdicionar.png"))); // NOI18N
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, 205, 50));

        campoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 320, 40));

        comboListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aniversariantes", "Pendentes", "Pagos", "Encerrados" }));
        getContentPane().add(comboListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 170, 30));

        comboTurmasExistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTurmasExistentesActionPerformed(evt);
            }
        });
        getContentPane().add(comboTurmasExistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 30));

        botaoPlanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnPlanos.png"))); // NOI18N
        botaoPlanos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnPlanosHover.png"))); // NOI18N
        botaoPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlanosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, -1));

        botaoPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnPais.png"))); // NOI18N
        botaoPais.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnPaishover.png"))); // NOI18N
        botaoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPaisActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, -1));

        botaoEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnEndereco.png"))); // NOI18N
        botaoEndereco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnEnderecohover.png"))); // NOI18N
        botaoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, -1));

        botaoAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnAlunosh.png"))); // NOI18N
        botaoAlunos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/btnAlunos.png"))); // NOI18N
        botaoAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, -1));

        planodefundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/Alunos.jpg"))); // NOI18N
        getContentPane().add(planodefundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        point.x = evt.getX();
        point.y = evt.getY();
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point p = this.getLocation();
        this.setLocation(p.x+ evt.getX()-point.x,p.y+ evt.getY()-point.y);
    }//GEN-LAST:event_formMouseDragged

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
    try {
        controller.editarAlunos();
    } catch (ParseException ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void tabelaAlunosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaAlunosComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAlunosComponentHidden

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        // TODO add your handling code here:
        telaAlunosCadastro.setModal(true);
        telaAlunosCadastro.setLocationRelativeTo(null);
        telaAlunosCadastro.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este aluno?", "Atenção",
                JOptionPane.YES_NO_OPTION);
        
        if(confirmacao == JOptionPane.YES_OPTION){
            try {
                controller.removerAluno();
            } catch (ParseException ex) {
                Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void tabelaPaisComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaPaisComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPaisComponentHidden

    private void tabelaEnderecosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaEnderecosComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaEnderecosComponentHidden

    private void botaoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPaisActionPerformed
        this.trocarTabelas(2);
        this.selecionarTabelas(2);
    }//GEN-LAST:event_botaoPaisActionPerformed

    private void botaoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnderecoActionPerformed
        this.trocarTabelas(3);
        this.selecionarTabelas(3);
    }//GEN-LAST:event_botaoEnderecoActionPerformed

    private void botaoAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunosActionPerformed
        this.trocarTabelas(4);
        this.selecionarTabelas(4);
    }//GEN-LAST:event_botaoAlunosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        controller.verificacaoDeTurmaEServico();
    } catch (SQLException ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    try {
        controller.listarAlunos();
    } catch (ParseException ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void botaobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobuscarActionPerformed
        
    try {
        controller.buscarAlunos();
    } catch (Exception ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_botaobuscarActionPerformed

    private void campoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            getRootPane().setDefaultButton(botaobuscar);
        }
    }//GEN-LAST:event_campoPesquisaKeyPressed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
    try {
        controller.listar();
    } catch (Exception ex) {
        Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlanosActionPerformed
        this.trocarTabelas(1);
        for(int linhas=0; linhas<painelPlanos.getComponentCount(); linhas++){
                painelPlanos.getComponent(linhas).setVisible(true);
        }
        this.selecionarTabelas(1);
    }//GEN-LAST:event_botaoPlanosActionPerformed

    private void tabelaPlanosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaPlanosComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPlanosComponentHidden

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
        this.selecionarTabelas(1);
        for(int linhas=0; linhas<painelPlanos.getComponentCount(); linhas++){
                painelPlanos.getComponent(linhas).setVisible(false);
        }
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaAlunosMouseClicked

    private void tabelaPlanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPlanosMouseClicked
        this.selecionarTabelas(2);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaPlanosMouseClicked

    private void tabelaPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPaisMouseClicked
        this.selecionarTabelas(3);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaPaisMouseClicked

    private void tabelaEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEnderecosMouseClicked
        this.selecionarTabelas(4);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaEnderecosMouseClicked

    private void tabelaAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaAlunosKeyReleased
        this.selecionarTabelas(1);
        for(int linhas=0; linhas<painelPlanos.getComponentCount(); linhas++){
            painelPlanos.getComponent(linhas).setVisible(false);
        }
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaAlunosKeyReleased

    private void tabelaPlanosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaPlanosKeyReleased
        this.selecionarTabelas(2);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaPlanosKeyReleased

    private void tabelaPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaPaisKeyReleased
        this.selecionarTabelas(3);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaPaisKeyReleased

    private void tabelaEnderecosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaEnderecosKeyReleased
        this.selecionarTabelas(4);
        controller.selecionarTabela();
    }//GEN-LAST:event_tabelaEnderecosKeyReleased

    private void comboTurmasExistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTurmasExistentesActionPerformed
        try {
            controller.listarAlunos();
        } catch (ParseException ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboTurmasExistentesActionPerformed

    private void botaoConfigAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfigAdicionaisActionPerformed
        
        
        
        
        Component[] frameComponents = this.getContentPane().getComponents();
        for(Component componente:frameComponents){
            componente.setEnabled(false);
        }
        
        try {
            controller.setarDatasConfiguracoesAd();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        painelConfiguracoesAdicionais.setEnabled(true);
        painelConfiguracoesAdicionais.setVisible(true);
    }//GEN-LAST:event_botaoConfigAdicionaisActionPerformed

    private void botaoFecharConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharConfActionPerformed
        // TODO add your handling code here:
        
        for(int linhas=0; linhas<painelAlunos.getComponentCount(); linhas++){
            painelAlunos.getComponent(linhas).setEnabled(true);
        }
        for(int linhas=0; linhas<painelPlanos.getComponentCount(); linhas++){
            painelPlanos.getComponent(linhas).setEnabled(true);
        }
        for(int linhas=0; linhas<painelPais.getComponentCount(); linhas++){
            painelPais.getComponent(linhas).setEnabled(true);
        }
        for(int linhas=0; linhas<painelEnderecos.getComponentCount(); linhas++){
            painelEnderecos.getComponent(linhas).setEnabled(true);
        }
        
        Component[] frameComponents = this.getContentPane().getComponents();
        for(Component componente:frameComponents){
            componente.setEnabled(true);
        }
        
        
        painelConfiguracoesAdicionais.setEnabled(false);
        painelConfiguracoesAdicionais.setVisible(false);
    }//GEN-LAST:event_botaoFecharConfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controller.setarDataVencimento();
        } catch (ParseException ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlunosView dialog = new AlunosView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAlunos;
    private javax.swing.JButton botaoConfigAdicionais;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoEndereco;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoFecharConf;
    private javax.swing.JButton botaoListar;
    private javax.swing.JButton botaoPais;
    private javax.swing.JButton botaoPlanos;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaobuscar;
    private javax.swing.JTextArea campoAvisoDataVencimento;
    private com.toedter.calendar.JDateChooser campoDataCadastro;
    private com.toedter.calendar.JDateChooser campoDataFimPlano;
    private com.toedter.calendar.JDateChooser campoDataPagamento;
    private com.toedter.calendar.JDateChooser campoDataVencimento;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JComboBox<String> comboListar;
    private javax.swing.JComboBox<String> comboTurmasExistentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane painelAlunos;
    private javax.swing.JPanel painelConfiguracoesAdicionais;
    private javax.swing.JScrollPane painelEnderecos;
    private javax.swing.JScrollPane painelPais;
    private javax.swing.JScrollPane painelPlanos;
    private javax.swing.JLabel planodefundo;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTable tabelaEnderecos;
    private javax.swing.JTable tabelaPais;
    private javax.swing.JTable tabelaPlanos;
    // End of variables declaration//GEN-END:variables

    private void trocarTabelas(int opcao){
        switch(opcao){
            case 1:
                this.botaoPlanos.setVisible(false);
                this.painelAlunos.setVisible(false);
                this.botaoPais.setVisible(true);
                this.painelPlanos.setVisible(true);
            break;
            
            case 2:
                this.botaoPais.setVisible(false);
                this.painelPlanos.setVisible(false);
                this.botaoEndereco.setVisible(true);
                this.painelPais.setVisible(true);
            break;
            
            case 3:
                this.botaoEndereco.setVisible(false);
                this.painelPais.setVisible(false);
                this.botaoAlunos.setVisible(true);
                this.painelEnderecos.setVisible(true);
            break;
            
            case 4:
                this.botaoAlunos.setVisible(false);
                this.painelEnderecos.setVisible(false);
                this.botaoPlanos.setVisible(true);
                this.painelAlunos.setVisible(true);
            break;
        }
        
    }
    
    public void exibeMensagem(String mensagem) {
      JOptionPane.showMessageDialog(null, mensagem);
    }
    
    private void setInicialBotoes(){
        this.botaoPais.setVisible(true);
        this.painelAlunos.setVisible(true);
        this.botaoEndereco.setVisible(false);
        this.painelPais.setVisible(false);
        this.botaoAlunos.setVisible(false);
        this.painelEnderecos.setVisible(false);
    }

    public JComboBox<String> getComboServicos() {
        return comboServicos;
    }

    public JComboBox<String> getComboTurmas() {
        return comboTurmas;
    }

    public JComboBox<String> getComboEstado() {
        return comboEstado;
    }


    public JTextField getCampoPesquisa() {
        return campoPesquisa;
    }

    public JComboBox<String> getComboListar() {
        return comboListar;
    }

    public JTable getTabelaAlunos() {
        return tabelaAlunos;
    }

    public JTable getTabelaEnderecos() {
        return tabelaEnderecos;
    }

    public JTable getTabelaPais() {
        return tabelaPais;
    }

    public JTable getTabelaPlanos() {
        return tabelaPlanos;
    }

    public int getNumeroTela() {
        return numeroTela;
    }

    public JComboBox<String> getComboTurmasExistentes() {
        return comboTurmasExistentes;
    }

    public JDateChooser getCampoDataCadastro() {
        return campoDataCadastro;
    }

    public JDateChooser getCampoDataPagamento() {
        return campoDataPagamento;
    }

    public JDateChooser getCampoDataVencimento() {
        return campoDataVencimento;
    }

    public JPanel getPainelConfiguracoesAdicionais() {
        return painelConfiguracoesAdicionais;
    }

    public JButton getBotaoConfigAdicionais() {
        return botaoConfigAdicionais;
    }

    public JTextArea getCampoAvisoDataVencimento() {
        return campoAvisoDataVencimento;
    }

    public JDateChooser getCampoDataFimPlano() {
        return campoDataFimPlano;
    }
    
    
    
    private void selecionarTabelas(int opcao){
        switch(opcao){
            case 1:
            if(tabelaAlunos.getSelectedRow()>-1){
            tabelaPlanos.addRowSelectionInterval(tabelaAlunos.getSelectedRow(), tabelaAlunos.getSelectedRow());
            tabelaPais.addRowSelectionInterval(tabelaAlunos.getSelectedRow(), tabelaAlunos.getSelectedRow());
            tabelaEnderecos.addRowSelectionInterval(tabelaAlunos.getSelectedRow(), tabelaAlunos.getSelectedRow());
            }
            break;
            
            case 2:
            if(tabelaPlanos.getSelectedRow()>-1){
            tabelaPais.addRowSelectionInterval(tabelaPlanos.getSelectedRow(), tabelaPlanos.getSelectedRow());
            tabelaEnderecos.addRowSelectionInterval(tabelaPlanos.getSelectedRow(), tabelaPlanos.getSelectedRow());
            tabelaAlunos.addRowSelectionInterval(tabelaPlanos.getSelectedRow(), tabelaPlanos.getSelectedRow());
            }
            break;
            
            case 3:
            if(tabelaPais.getSelectedRow()>-1){
            tabelaEnderecos.addRowSelectionInterval(tabelaPais.getSelectedRow(), tabelaPais.getSelectedRow());
            tabelaAlunos.addRowSelectionInterval(tabelaPais.getSelectedRow(), tabelaPais.getSelectedRow());
            tabelaPlanos.addRowSelectionInterval(tabelaPais.getSelectedRow(), tabelaPais.getSelectedRow());
            }
            break;
            
            case 4:
            if(tabelaEnderecos.getSelectedRow()>-1){
            tabelaAlunos.addRowSelectionInterval(tabelaEnderecos.getSelectedRow(), tabelaEnderecos.getSelectedRow());
            tabelaPlanos.addRowSelectionInterval(tabelaEnderecos.getSelectedRow(), tabelaEnderecos.getSelectedRow());
            tabelaPais.addRowSelectionInterval(tabelaEnderecos.getSelectedRow(), tabelaEnderecos.getSelectedRow());
            }
            break;
        }
    }
    
    
    public void fecharTelaESC() {
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    public Frame getParent() {
        return parent;
    }
    
    private void setarComposicaoTabelas(){
        //Variáveis
        JFormattedTextField telefonePai = new JFormattedTextField();
        JFormattedTextField cpfPai = new JFormattedTextField();
        JFormattedTextField telefoneMae = new JFormattedTextField();
        JFormattedTextField cpfMae = new JFormattedTextField();
        JFormattedTextField cep = new JFormattedTextField();
        
        try {
            //Transformação de variáveis
            cpfPai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            cpfMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            telefonePai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
            telefoneMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
            comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Nenhum]", "AC", "AL", "AM", "AP", "BA", "CE", 
            "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RO", "RN", "RR", "RS", "SC", "SE", "SP", "TO" }));
            
        } catch (ParseException ex) {
            Logger.getLogger(AlunosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Alunos
        tabelaAlunos.getTableHeader().setResizingAllowed(true);
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        tabelaAlunos.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboTurmas));
        tabelaAlunos.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JMoneyField()));
        
        //Planos
        tabelaPlanos.getTableHeader().setResizingAllowed(true);
        tabelaPlanos.getTableHeader().setReorderingAllowed(false);
        tabelaPlanos.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(comboServicos));
        tabelaPlanos.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(new JMoneyField()));
        tabelaPlanos.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JMoneyField()));
        tabelaPlanos.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(new FormatacaodeCamposRestritos(2)));
        
        
        
        //Pais
        tabelaPais.getTableHeader().setResizingAllowed(true);
        tabelaPais.getTableHeader().setReorderingAllowed(false);
        tabelaPais.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(cpfPai));
        tabelaPais.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(telefonePai));
        tabelaPais.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cpfMae));
        tabelaPais.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(telefoneMae));
        
        //Enderecos
        tabelaEnderecos.getTableHeader().setResizingAllowed(true);
        tabelaEnderecos.getTableHeader().setReorderingAllowed(false);
        tabelaEnderecos.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(comboEstado));
        tabelaEnderecos.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(cep));
        
    }
}
