/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CaixaController;
import Controller.auxiliar.FormatacaoCamposRestritosLetras;
import Controller.auxiliar.FormatacaodeCamposRestritos;
import Controller.auxiliar.JMoneyField;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 55989
 */
public class Caixa extends javax.swing.JFrame {
    private final CaixaController controller;

    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
        controller = new CaixaController(this);
        botaoBuscarCliente.setBackground(new Color(0,0,0,0));
        botaoBuscarProdutos.setBackground(new Color(0,0,0,0));
        btnAdicionar.setBackground(new Color(0,0,0,0));
        botaoPagamentoMensalidade.setBackground(new Color(0,0,0,0));
        btnPlanoDePagamento.setBackground(new Color(0,0,0,0));
        btnFinalizar.setBackground(new Color(0,0,0,0));
        botaoConfirmar.setBackground(new Color(0,0,0,0));
        btnCancelar.setBackground(new Color(0,0,0,0));
        setExtendedState(MAXIMIZED_BOTH);
        this.setarComponentes();
        painelTabelaProdutos.setVisible(true);
        painelPagamentoMensal.setVisible(false);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/rehabi.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alternarClienteCadastrado = new javax.swing.JRadioButton();
        alternarClienteSemCadastro = new javax.swing.JRadioButton();
        alternarProdCodigo = new javax.swing.JRadioButton();
        alternarProdNome = new javax.swing.JRadioButton();
        campoCliente = new FormatacaoCamposRestritosLetras();
        botaoBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeClientes = new javax.swing.JTable();
        painelPagamentoMensal = new javax.swing.JPanel();
        campoPesquisa = new javax.swing.JTextField();
        botaobuscar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaMensalidade = new javax.swing.JTable();
        botaoConfirmar = new javax.swing.JButton();
        painelTabelaProdutos = new javax.swing.JScrollPane();
        tabelaDeCarrinho = new javax.swing.JTable();
        campoProdutoNome = new FormatacaoCamposRestritosLetras();
        campoProdutoCodigo = new FormatacaodeCamposRestritos();
        botaoBuscarProdutos = new javax.swing.JButton();
        campoQuantidade = new JMoneyField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDeProdutos = new javax.swing.JTable();
        btnPlanoDePagamento = new javax.swing.JButton();
        botaoPagamentoMensalidade = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        campoVPago = new JMoneyField();
        jLabel8 = new javax.swing.JLabel();
        campoVDesconto = new JMoneyField();
        jLabel7 = new javax.swing.JLabel();
        campoVTroco = new JMoneyField();
        jLabel6 = new javax.swing.JLabel();
        campoVTotal = new JMoneyField();
        jLabel2 = new javax.swing.JLabel();
        Fundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alternarClienteCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternarClienteCadastradoActionPerformed(evt);
            }
        });
        getContentPane().add(alternarClienteCadastrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 25, 20));

        alternarClienteSemCadastro.setSelected(true);
        alternarClienteSemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternarClienteSemCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(alternarClienteSemCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 25, 20));

        alternarProdCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternarProdCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(alternarProdCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 312, -1, -1));

        alternarProdNome.setSelected(true);
        alternarProdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternarProdNomeActionPerformed(evt);
            }
        });
        getContentPane().add(alternarProdNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 345, -1, -1));

        campoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoClienteKeyPressed(evt);
            }
        });
        getContentPane().add(campoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 190, 40));

        botaoBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscar.png"))); // NOI18N
        botaoBuscarCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscarHover.png"))); // NOI18N
        botaoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 50, 40));

        tabelaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Cliente", "Turma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDeClientes.getTableHeader().setResizingAllowed(false);
        tabelaDeClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaDeClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 480, 150));

        painelPagamentoMensal.setBackground(new java.awt.Color(0, 134, 191));
        painelPagamentoMensal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPesquisaKeyPressed(evt);
            }
        });
        painelPagamentoMensal.add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 320, 40));

        botaobuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscar.png"))); // NOI18N
        botaobuscar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscarHover.png"))); // NOI18N
        botaobuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobuscar2ActionPerformed(evt);
            }
        });
        painelPagamentoMensal.add(botaobuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 40));

        tabelaMensalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Aluno", "Serviço", "Vencimento", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMensalidade.getTableHeader().setResizingAllowed(false);
        tabelaMensalidade.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaMensalidade);

        painelPagamentoMensal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 170));

        botaoConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/cadastroalunos/botaoConfirmar.png"))); // NOI18N
        botaoConfirmar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/cadastroalunos/botaoConfirmarHover.png"))); // NOI18N
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        painelPagamentoMensal.add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 330, 60));

        getContentPane().add(painelPagamentoMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 870, 310));

        tabelaDeCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Produto", "Valor", "Quant.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDeCarrinho.getTableHeader().setResizingAllowed(false);
        tabelaDeCarrinho.getTableHeader().setReorderingAllowed(false);
        painelTabelaProdutos.setViewportView(tabelaDeCarrinho);

        getContentPane().add(painelTabelaProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 860, 200));

        campoProdutoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoProdutoNomeKeyPressed(evt);
            }
        });
        getContentPane().add(campoProdutoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, 40));
        getContentPane().add(campoProdutoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, 40));

        botaoBuscarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscar.png"))); // NOI18N
        botaoBuscarProdutos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscarHover.png"))); // NOI18N
        botaoBuscarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 50, 40));
        getContentPane().add(campoQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 362, 70, 40));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/btnAdicionar.png"))); // NOI18N
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 360, 160, -1));

        tabelaDeProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Produto", "Valor", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDeProdutos.getTableHeader().setResizingAllowed(false);
        tabelaDeProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaDeProdutos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 480, 130));

        btnPlanoDePagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/btnPlanodePagamento.png"))); // NOI18N
        btnPlanoDePagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlanoDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanoDePagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlanoDePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 560, 190, -1));

        botaoPagamentoMensalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/btnPagamentodeMensalidade.png"))); // NOI18N
        botaoPagamentoMensalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPagamentoMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPagamentoMensalidadeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPagamentoMensalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 250, -1));

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/btnFinalizar.png"))); // NOI18N
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1165, 610, 160, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/btnCancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 660, 150, -1));

        campoVPago.setEditable(false);
        getContentPane().add(campoVPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 662, 95, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("R$");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 662, 38, 40));

        campoVDesconto.setEditable(false);
        getContentPane().add(campoVDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 583, 95, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("R$");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 583, 38, 40));

        campoVTroco.setEditable(false);
        getContentPane().add(campoVTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1188, 497, 95, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("R$");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 497, 38, 40));

        campoVTotal.setEditable(false);
        getContentPane().add(campoVTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 497, 95, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("R$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 497, 38, 40));

        Fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/fundo.jpg"))); // NOI18N
        getContentPane().add(Fundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarClienteActionPerformed
        try {
            controller.setarTabelaClientes();
        } catch (Exception ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoBuscarClienteActionPerformed

    private void botaoBuscarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarProdutosActionPerformed
        try {
            controller.setarTabelaProdutos();
        } catch (Exception ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoBuscarProdutosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void botaoPagamentoMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPagamentoMensalidadeActionPerformed
        if(painelPagamentoMensal.isVisible()){
        painelPagamentoMensal.setVisible(false);
        painelTabelaProdutos.setVisible(true);
        
        }else{
        painelPagamentoMensal.setVisible(true);
        painelTabelaProdutos.setVisible(false);
        }
        
      
                
    }//GEN-LAST:event_botaoPagamentoMensalidadeActionPerformed

    private void btnPlanoDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanoDePagamentoActionPerformed
        // TODO add your handling code here:
        CaixaPlanoDePagamento abrir=new CaixaPlanoDePagamento();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnPlanoDePagamentoActionPerformed

    private void campoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisaKeyPressed

    }//GEN-LAST:event_campoPesquisaKeyPressed

    private void botaobuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobuscar2ActionPerformed

    }//GEN-LAST:event_botaobuscar2ActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed

    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void alternarClienteCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternarClienteCadastradoActionPerformed
        alternarClienteSemCadastro.setSelected(false);
        campoCliente.setEnabled(true);
        botaoBuscarCliente.setEnabled(true);
        botaoPagamentoMensalidade.setVisible(true);
        painelPagamentoMensal.setVisible(false);
        painelTabelaProdutos.setVisible(true);
    }//GEN-LAST:event_alternarClienteCadastradoActionPerformed

    private void alternarClienteSemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternarClienteSemCadastroActionPerformed
        alternarClienteCadastrado.setSelected(false);
        campoCliente.setText("");
        campoCliente.setEnabled(false);
        botaoBuscarCliente.setEnabled(false);
        botaoPagamentoMensalidade.setVisible(false);
        painelPagamentoMensal.setVisible(false);
        painelTabelaProdutos.setVisible(true);
    }//GEN-LAST:event_alternarClienteSemCadastroActionPerformed

    private void alternarProdCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternarProdCodigoActionPerformed
        alternarProdNome.setSelected(false);
        campoProdutoNome.setText("");
        campoProdutoNome.setVisible(false);
        campoProdutoCodigo.setVisible(true);
    }//GEN-LAST:event_alternarProdCodigoActionPerformed

    private void alternarProdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternarProdNomeActionPerformed
        alternarProdCodigo.setSelected(false);
        campoProdutoCodigo.setText("");
        campoProdutoCodigo.setVisible(false);
        campoProdutoNome.setVisible(true);
    }//GEN-LAST:event_alternarProdNomeActionPerformed

    private void campoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoClienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            getRootPane().setDefaultButton(botaoBuscarCliente);
        }
    }//GEN-LAST:event_campoClienteKeyPressed

    private void campoProdutoNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoProdutoNomeKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            getRootPane().setDefaultButton(botaoBuscarProdutos);
        }
    }//GEN-LAST:event_campoProdutoNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo1;
    private javax.swing.JRadioButton alternarClienteCadastrado;
    private javax.swing.JRadioButton alternarClienteSemCadastro;
    private javax.swing.JRadioButton alternarProdCodigo;
    private javax.swing.JRadioButton alternarProdNome;
    private javax.swing.JButton botaoBuscarCliente;
    private javax.swing.JButton botaoBuscarProdutos;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoPagamentoMensalidade;
    private javax.swing.JButton botaobuscar2;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPlanoDePagamento;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JTextField campoProdutoCodigo;
    private javax.swing.JTextField campoProdutoNome;
    private javax.swing.JFormattedTextField campoQuantidade;
    private javax.swing.JFormattedTextField campoVDesconto;
    private javax.swing.JFormattedTextField campoVPago;
    private javax.swing.JFormattedTextField campoVTotal;
    private javax.swing.JFormattedTextField campoVTroco;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painelPagamentoMensal;
    private javax.swing.JScrollPane painelTabelaProdutos;
    private javax.swing.JTable tabelaDeCarrinho;
    private javax.swing.JTable tabelaDeClientes;
    private javax.swing.JTable tabelaDeProdutos;
    private javax.swing.JTable tabelaMensalidade;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
      JOptionPane.showMessageDialog(null, mensagem);
    }
    
    private void setarComponentes(){
        campoCliente.setEnabled(false);
        botaoBuscarCliente.setEnabled(false);
        botaoPagamentoMensalidade.setVisible(false);
        
        campoProdutoCodigo.setVisible(false);
        campoProdutoNome.setVisible(true);
    }

    public JTextField getCampoCliente() {
        return campoCliente;
    }

    public JTextField getCampoPesquisa() {
        return campoPesquisa;
    }

    public JTextField getCampoProdutoCodigo() {
        return campoProdutoCodigo;
    }

    public JTextField getCampoProdutoNome() {
        return campoProdutoNome;
    }

    public JFormattedTextField getCampoQuantidade() {
        return campoQuantidade;
    }

    public JFormattedTextField getCampoVDesconto() {
        return campoVDesconto;
    }

    public JFormattedTextField getCampoVPago() {
        return campoVPago;
    }

    public JFormattedTextField getCampoVTotal() {
        return campoVTotal;
    }

    public JFormattedTextField getCampoVTroco() {
        return campoVTroco;
    }

    public JTable getTabelaDeCarrinho() {
        return tabelaDeCarrinho;
    }

    public JTable getTabelaDeClientes() {
        return tabelaDeClientes;
    }

    public JTable getTabelaDeProdutos() {
        return tabelaDeProdutos;
    }

    public JTable getTabelaMensalidade() {
        return tabelaMensalidade;
    }
    
}
