/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Paineis.GastosDetalhesController;
import Controller.PlanoGastosController;
import View.Paineis.GastosDetalhes;
import View.Paineis.PainelAjuda;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;

/**
 *
 * @author 55989
 */
public class FinanceiroPlanodeContra extends javax.swing.JDialog {
    private final java.awt.Frame parent;
    private final PlanoGastosController controller;
    private final GastosDetalhesController controllerDetalhes;
    private final FinanceiroPlanodeContraAdc telaContraAdicionar;
    private final GastosDetalhes gastosDetalhes;
    private final PainelAjuda painelAjuda;

    /**
     * Creates new form FinanceiroPlanodeContra
     * @param parent
     * @param modal
     */
    public FinanceiroPlanodeContra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        telaContraAdicionar= new FinanceiroPlanodeContraAdc(parent, false);
        painelAjuda = new PainelAjuda(parent, false, this.getLocation().x+this.getSize().width+4, this.getLocation().y);
        gastosDetalhes = new GastosDetalhes(this, parent, false);
        
        
        
        controller = new PlanoGastosController(this);
        controllerDetalhes = new GastosDetalhesController(this, gastosDetalhes);
        botaoFechar.setBackground(new Color(0,0,0,0));
        btnAdicionar.setBackground(new Color(0,0,0,0));
        btnAplicar.setBackground(new Color(0,0,0,0));
        botaoVDetalhada.setBackground(new Color(0,0,0,0));
        btnRemover.setBackground(new Color(0,0,0,0));
        botaoVResumida.setBackground(new Color(0,0,0,0));
        this.setarComponentes();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/rehabi.png")).getImage());
        
        //Fechar a tela quando pressionar ESC
        this.teclasDeAtalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFechar = new javax.swing.JButton();
        campoDataEspecífica = new com.toedter.calendar.JDateChooser();
        painelGastos = new javax.swing.JScrollPane();
        tabelaGastos = new javax.swing.JTable();
        comboPeriodo = new javax.swing.JComboBox<>();
        comboTipos = new javax.swing.JComboBox<>();
        comboPagamento = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        botaoVResumida = new javax.swing.JButton();
        botaoVDetalhada = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        botaoAjuda = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(873, 700));
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaofechar.png"))); // NOI18N
        botaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFechar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverfechar.png"))); // NOI18N
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 220, 50));
        getContentPane().add(campoDataEspecífica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, -1));

        tabelaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codBanco", "Referência", "Valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaGastos.setFocusable(false);
        tabelaGastos.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaGastos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaGastos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaGastos.setShowVerticalLines(false);
        tabelaGastos.getTableHeader().setReorderingAllowed(false);
        tabelaGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaGastosMouseClicked(evt);
            }
        });
        tabelaGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaGastosKeyReleased(evt);
            }
        });
        painelGastos.setViewportView(tabelaGastos);

        getContentPane().add(painelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 811, 340));

        comboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Nenhum]", "Diário", "Semanal", "Mensal", "Semestral", "Anual" }));
        comboPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(comboPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 140, -1));

        comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contra-Serviços", "Pagamento Salarial" }));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });
        getContentPane().add(comboTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 120, -1));

        comboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Nenhum]", "Dinheiro", "Boleto", "Cartão de Crédito", "Cartão de Débito" }));
        getContentPane().add(comboPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 130, -1));

        btnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnAplicar.png"))); // NOI18N
        btnAplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnAplicarHover.png"))); // NOI18N
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 146, 35));

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnRemover.png"))); // NOI18N
        btnRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemover.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnRemoverHover.png"))); // NOI18N
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 146, 34));

        botaoVResumida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnResumido.png"))); // NOI18N
        botaoVResumida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVResumida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnResumidoHover.png"))); // NOI18N
        botaoVResumida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVResumidaMouseClicked(evt);
            }
        });
        getContentPane().add(botaoVResumida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 146, 34));

        botaoVDetalhada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnDetalhada.png"))); // NOI18N
        botaoVDetalhada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVDetalhada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnDetalhadaHover.png"))); // NOI18N
        botaoVDetalhada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVDetalhadaMouseClicked(evt);
            }
        });
        getContentPane().add(botaoVDetalhada, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 146, 34));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnAdicionar.png"))); // NOI18N
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro/btnAdicionarHover.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 146, 34));

        botaoAjuda.setBackground(new java.awt.Color(255, 255, 255));
        botaoAjuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAjuda.setForeground(new java.awt.Color(255, 255, 255));
        botaoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/btnDuvidas.png"))); // NOI18N
        botaoAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 30, 30));

        botaoEditar.setText("...");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 354, 20, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 13, 138));
        jLabel2.setText("TIPOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 13, 138));
        jLabel3.setText("PAGAMENTO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 13, 138));
        jLabel4.setText("VERSÕES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 13, 138));
        jLabel5.setText("PERÍODO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/planodecontraservicosFINAL.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        if(gastosDetalhes.isVisible()){
            controllerDetalhes.sairTela();
        }
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaContraAdicionar.setModal(true);
        telaContraAdicionar.setLocationRelativeTo(null);
        telaContraAdicionar.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void botaoVResumidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVResumidaMouseClicked
        botaoVResumida.setEnabled(true);
        botaoVDetalhada.setEnabled(false);
        if(botaoEditar.isVisible()){
            botaoEditar.setVisible(false);
        }
    }//GEN-LAST:event_botaoVResumidaMouseClicked

    private void botaoVDetalhadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVDetalhadaMouseClicked
        botaoVDetalhada.setEnabled(true);
        botaoVResumida.setEnabled(false);
        if(botaoEditar.isVisible()){
            botaoEditar.setVisible(false);
        }
    }//GEN-LAST:event_botaoVDetalhadaMouseClicked

    private void comboPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPeriodoActionPerformed
        if(comboPeriodo.getSelectedIndex()>0){
            comboTipos.setSelectedIndex(0);
            comboTipos.setEnabled(true);
            campoDataEspecífica.setDate(null);
            campoDataEspecífica.setEnabled(false);
        }
        else{
            campoDataEspecífica.setDate(null);
            campoDataEspecífica.setEnabled(true);
            comboTipos.setSelectedIndex(0);
            comboTipos.setEnabled(true);
            comboPagamento.setSelectedIndex(0);
            comboPagamento.setEnabled(true);
        }
    }//GEN-LAST:event_comboPeriodoActionPerformed

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        comboPagamento.setSelectedIndex(0);
        comboPagamento.setEnabled(true);
    }//GEN-LAST:event_comboTiposActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        controller.setarTabelas();
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        controller.removerGasto();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             setVisible(false);
        }
    }//GEN-LAST:event_formKeyPressed

    private void botaoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaActionPerformed
        controller.ajuda();
    }//GEN-LAST:event_botaoAjudaActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        if(!gastosDetalhes.isVisible()){
            controllerDetalhes.selecionarTabela();
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void tabelaGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaGastosMouseClicked
        controllerDetalhes.releasedTable();
        if(tabelaGastos.getSelectedRow()!=-1&&botaoVDetalhada.isEnabled()){
            setarBotaoEditar(true, evt.getYOnScreen());
        }else{
            setarBotaoEditar(false, 0);
        }
    }//GEN-LAST:event_tabelaGastosMouseClicked

    private void tabelaGastosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaGastosKeyReleased
        controllerDetalhes.releasedTable();
    }//GEN-LAST:event_tabelaGastosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceiroPlanodeContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceiroPlanodeContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceiroPlanodeContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceiroPlanodeContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FinanceiroPlanodeContra dialog = new FinanceiroPlanodeContra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAjuda;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoVDetalhada;
    private javax.swing.JButton botaoVResumida;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnRemover;
    private com.toedter.calendar.JDateChooser campoDataEspecífica;
    private javax.swing.JComboBox<String> comboPagamento;
    private javax.swing.JComboBox<String> comboPeriodo;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane painelGastos;
    private javax.swing.JTable tabelaGastos;
    // End of variables declaration//GEN-END:variables
    
    public void exibeMensagem(String mensagem) {
      JOptionPane.showMessageDialog(null, mensagem);
    }
    
    public void mensagemCritica(String mensagem, String titulo){
       JOptionPane.showMessageDialog(null, mensagem, titulo, JOptionPane.WARNING_MESSAGE);
    }
    
        private void setarComponentes(){
        //combos
        comboTipos.setSelectedIndex(0);
        comboTipos.setEnabled(false);
        comboPagamento.setSelectedIndex(0);
        comboPagamento.setEnabled(false);
        
        //botões
        botaoVResumida.setEnabled(true);
        botaoVDetalhada.setEnabled(false);
        
        campoDataEspecífica.setEnabled(false);
        this.setarBotaoEditar(false, 0);
    }

    public JButton getBotaoVDetalhada() {
        return botaoVDetalhada;
    }

    public JButton getBotaoVResumida() {
        return botaoVResumida;
    }

    public JComboBox<String> getComboPagamento() {
        return comboPagamento;
    }

    public JComboBox<String> getComboPeriodo() {
        return comboPeriodo;
    }

    public JComboBox<String> getComboTipos() {
        return comboTipos;
    }

    public JTable getTabelaGastos() {
        return tabelaGastos;
    }

    public JScrollPane getPainelGastos() {
        return painelGastos;
    }

    public JDateChooser getCampoDataEspecífica() {
        return campoDataEspecífica;
    }

    public Frame getParent() {
        return parent;
    }

    public PainelAjuda getPainelAjuda() {
        return painelAjuda;
    }
    
    private void setarBotaoEditar(boolean visible, int y){
        
        if(visible){
            int cont=370;
            while(cont<=670){
                if(y>=cont&&y<cont+15){
                    botaoEditar.setLocation(botaoEditar.getX(), cont-16);
                    botaoEditar.setVisible(visible);
                    break;
                }
                cont+=15;
            }  
        }
        else{
            botaoEditar.setVisible(false);
        }
    }
    
    private void teclasDeAtalho() {
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        this.conjuntoTeclasAtalho(meurootpane);
    }
    
    private void conjuntoTeclasAtalho(JRootPane meurootpane){
        //Fechar Sistema
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("alt F4"), "FECHAR");
        meurootpane.getRootPane().getActionMap().put("FECHAR", new AbstractAction("FECHAR") {
            @Override
            public void actionPerformed(ActionEvent e) {
                int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Deseja Realmente encerrar esta sessão", "Nota", JOptionPane.YES_NO_OPTION);
                if(showConfirmDialog == JOptionPane.YES_OPTION){
                    if(gastosDetalhes.isVisible()){
                        controllerDetalhes.sairTela();
                    }
                    controller.sairTela();
                }
            }
        });
        
        //Adicionar Novo
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ctrl N"), "NOVO");
        meurootpane.getRootPane().getActionMap().put("NOVO", new AbstractAction("NOVO") {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(gastosDetalhes.isVisible()){
                    controllerDetalhes.sairTela();
                }
                telaContraAdicionar.setModal(true);
                telaContraAdicionar.setLocationRelativeTo(null);
                telaContraAdicionar.setVisible(true);
            }
        });
        
        //Editar Gasto
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ctrl E"), "EDITARGASTO");
        meurootpane.getRootPane().getActionMap().put("EDITARGASTO", new AbstractAction("EDITARGASTO") {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(gastosDetalhes.isVisible()){
                    controllerDetalhes.sairTela();
                }
                controller.editarGasto();
            }
        });
    }
    
}
