/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.adicionais.ReposicaoController;
import Controller.auxiliar.FormatacaoCamposRestritosLetras;
import com.sun.glass.events.KeyEvent;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author 55989
 */
public class ReposicaoView extends javax.swing.JDialog {
    private final java.awt.Frame parent;
    private final HistoricoRehab telaHistorico;
    private final ReposicaoController controller;
    /**
     * Creates new form ReposicaoView
     * @param parent
     * @param modal
     */
    public ReposicaoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.telaHistorico = new HistoricoRehab(parent, false);
        
        controller = new ReposicaoController(this);
        
        botaoFechar.setBackground(new Color(0,0,0,0));
        botaobuscar.setBackground(new Color(0,0,0,0));
        botaoAdicionar.setBackground(new Color(0,0,0,0));
        btnHist.setBackground(new Color(0,0,0,0));
        
        ativarDesabilitarComponentes(false);
        atalhosTeclado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFechar = new javax.swing.JButton();
        campoPesquisa = new FormatacaoCamposRestritosLetras();
        botaobuscar = new javax.swing.JButton();
        comboDiaDaSemana = new javax.swing.JComboBox<>();
        comboTurma = new javax.swing.JComboBox<>();
        btnHist = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        jLabelDInicio = new javax.swing.JLabel();
        campoDataInicio = new com.toedter.calendar.JDateChooser();
        campoDataFim = new com.toedter.calendar.JDateChooser();
        jLabelDFim = new javax.swing.JLabel();
        comboTurmasExistentes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgendamento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAgendados = new javax.swing.JTable();
        botaoTodasReposicoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaofechar.png"))); // NOI18N
        botaoFechar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoHoverfechar.png"))); // NOI18N
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 220, 50));

        campoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 320, 35));

        botaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscar.png"))); // NOI18N
        botaobuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoBuscarHover.png"))); // NOI18N
        botaobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botaobuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 50, 35));

        comboDiaDaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaDaSemanaActionPerformed(evt);
            }
        });
        getContentPane().add(comboDiaDaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 90, 35));

        comboTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 320, 35));

        btnHist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reposicao/btnHisto.png"))); // NOI18N
        btnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistActionPerformed(evt);
            }
        });
        getContentPane().add(btnHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, 40));

        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos/botaoAdicionar.png"))); // NOI18N
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 250, 50));

        jLabelDInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDInicio.setText("Data Início");
        getContentPane().add(jLabelDInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        getContentPane().add(campoDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 30));
        getContentPane().add(campoDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, 30));

        jLabelDFim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDFim.setText("Data Fim");
        getContentPane().add(jLabelDFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        comboTurmasExistentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Nenhuma]" }));
        getContentPane().add(comboTurmasExistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 220, 35));

        tabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Nome", "Turma Atual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgendamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAgendamento.getTableHeader().setReorderingAllowed(false);
        tabelaAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabelaAgendamentoFocusLost(evt);
            }
        });
        tabelaAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAgendamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 370, 120));

        tabelaAgendados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBanco", "Data", "Aluno", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgendados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabelaAgendados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 420, 370));

        botaoTodasReposicoes.setText("Exibir Todas");
        botaoTodasReposicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTodasReposicoesActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTodasReposicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reposicao/fundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void campoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisaKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        getRootPane().setDefaultButton(botaobuscar);
    }
        
    }//GEN-LAST:event_campoPesquisaKeyPressed

    private void botaobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobuscarActionPerformed
        controller.pesquisarAluno();
    }//GEN-LAST:event_botaobuscarActionPerformed

    private void btnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistActionPerformed
        telaHistorico.setModal(true);
        telaHistorico.setLocationRelativeTo(null);
        telaHistorico.setVisible(true);
    }//GEN-LAST:event_btnHistActionPerformed

    private void tabelaAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendamentoMouseClicked
        controller.selecionarTabelaAgendamento();
    }//GEN-LAST:event_tabelaAgendamentoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controller.listarTurmas();
    }//GEN-LAST:event_formWindowOpened

    private void tabelaAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaAgendamentoFocusLost
        controller.selecionarTabelaAgendamento();
    }//GEN-LAST:event_tabelaAgendamentoFocusLost

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        controller.adicionarAgendamento();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void comboTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTurmaActionPerformed
        if(comboTurma.getSelectedIndex()==0){
            comboDiaDaSemana.removeAllItems();
        }
        controller.listarHorarios();
    }//GEN-LAST:event_comboTurmaActionPerformed

    private void comboDiaDaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaDaSemanaActionPerformed
        controller.setarTabelaAgendados();
    }//GEN-LAST:event_comboDiaDaSemanaActionPerformed

    private void botaoTodasReposicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTodasReposicoesActionPerformed
        controller.exibirFuturasReposicoes();
    }//GEN-LAST:event_botaoTodasReposicoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReposicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReposicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReposicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReposicaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReposicaoView dialog = new ReposicaoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoTodasReposicoes;
    private javax.swing.JButton botaobuscar;
    private javax.swing.JButton btnHist;
    private com.toedter.calendar.JDateChooser campoDataFim;
    private com.toedter.calendar.JDateChooser campoDataInicio;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JComboBox<String> comboDiaDaSemana;
    private javax.swing.JComboBox<String> comboTurma;
    private javax.swing.JComboBox<String> comboTurmasExistentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDFim;
    private javax.swing.JLabel jLabelDInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaAgendados;
    private javax.swing.JTable tabelaAgendamento;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
      JOptionPane.showMessageDialog(null, mensagem);
    }
    
        public void atalhosTeclado() {
        //sair
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        
        //atualizar
        JRootPane meurootpane1 = getRootPane();
        meurootpane1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0), "F5");
        meurootpane1.getRootPane().getActionMap().put("F5", new AbstractAction("F5") {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.listarTurmas();
            }
        });
        
        //Deletar Reposição
        JRootPane meurootpane2 = getRootPane();
        meurootpane2.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0), "DELETE");
        meurootpane2.getRootPane().getActionMap().put("DELETE", new AbstractAction("DELETE") {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.removerReposicao();
            }
        });
        
        //Editar uma Reposição
        JRootPane meurootpane3 = getRootPane();
        meurootpane3.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0), "F1");
        meurootpane3.getRootPane().getActionMap().put("F1", new AbstractAction("F1") {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.editarAluno();
            }
        });
        
        //Editar várias Reposições
        JRootPane meurootpane4 = getRootPane();
        meurootpane4.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0), "F3");
        meurootpane4.getRootPane().getActionMap().put("F3", new AbstractAction("F3") {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.editarVariosAlunos();
            }
        });
    }
    
    public JDateChooser getCampoDataFim() {
        return campoDataFim;
    }

    public JDateChooser getCampoDataInicio() {
        return campoDataInicio;
    }

    public JTextField getCampoPesquisa() {
        return campoPesquisa;
    }

    public JComboBox<String> getComboDiaDaSemana() {
        return comboDiaDaSemana;
    }

    public JComboBox<String> getComboTurma() {
        return comboTurma;
    }

    public JComboBox<String> getComboTurmasExistentes() {
        return comboTurmasExistentes;
    }

    public JTable getTabelaAgendados() {
        return tabelaAgendados;
    }

    public JTable getTabelaAgendamento() {
        return tabelaAgendamento;
    }
    
    public void ativarDesabilitarComponentes(boolean opcao){
        this.jLabelDInicio.setVisible(opcao);
        this.jLabelDFim.setVisible(opcao);
        this.campoDataFim.setVisible(opcao);
        this.campoDataInicio.setVisible(opcao);
        this.comboTurmasExistentes.setVisible(opcao);
        this.botaoAdicionar.setVisible(opcao);
    }
}
