/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.adicionais.TelaInicioGerenteController;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author 55989
 */
public class TelaInicialGerenteView extends javax.swing.JFrame {
    private final TelaInicioGerenteController controller;
    private final AlunosView telaAlunos;
    private final TurmasView telaTurmas;
    private final turmasFrequencia telaTurmasFrequencia;
    private final ProdutosView telaProdutos;
    private final ServicosView telaServicos;

    /**
     * Creates new form telaInicialGerente
     */
    public TelaInicialGerenteView() {
        initComponents();
        
        telaAlunos=new AlunosView(this, true);
        telaTurmas=new TurmasView(this, true);
        telaTurmasFrequencia= new turmasFrequencia(this, true);
        telaProdutos=new ProdutosView(this, true);
        telaServicos=new ServicosView(this, true);
        
        
        menuGerente.setVisible(false);
        menuGerente.setBackground(new Color(0,0,0,0));
        controller = new TelaInicioGerenteController(this);
        botaoSair.setBackground(new Color(0,0,0,0));
        botaoCaixa.setBackground(new Color(0,0,0,0));
        botaoAlunos.setBackground(new Color(0,0,0,0));
        botaoFinanceiro.setBackground(new Color(0,0,0,0));
        botaoFrequencia.setBackground(new Color(0,0,0,0));
        botaoMenu.setBackground(new Color(0,0,0,0));
        botaoFuncionarios.setBackground(new Color(0,0,0,0));
        jScrollPane1.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        
        
        botaoFechar.setBackground(new Color(0,0,0,0));
        botaoSair1.setBackground(new Color(0,0,0,0));
        botaoAlunos1.setBackground(new Color(0,0,0,0));
        botaoTurmas.setBackground(new Color(0,0,0,0));
        botaoProdutos.setBackground(new Color(0,0,0,0));
        botaoServicos.setBackground(new Color(0,0,0,0));
        botaoFinanceiro1.setBackground(new Color(0,0,0,0));
        botaoBackup.setBackground(new Color(0,0,0,0));
        botaoImprimirExportar.setBackground(new Color(0,0,0,0));
        botaoCaixa1.setBackground(new Color(0,0,0,0));
        
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/rehabi.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuGerente = new javax.swing.JPanel();
        botaoFechar = new javax.swing.JButton();
        botaoBackup = new javax.swing.JButton();
        botaoImprimirExportar = new javax.swing.JButton();
        botaoFinanceiro1 = new javax.swing.JButton();
        botaoServicos = new javax.swing.JButton();
        botaoTurmas = new javax.swing.JButton();
        botaoAlunos1 = new javax.swing.JButton();
        botaoProdutos = new javax.swing.JButton();
        botaoCaixa1 = new javax.swing.JButton();
        botaoSair1 = new javax.swing.JButton();
        planodefundo1 = new javax.swing.JLabel();
        botaoFuncionarios = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoCaixa = new javax.swing.JButton();
        animaçãoRehabiliter = new javax.swing.JLabel();
        botaoAlunos = new javax.swing.JButton();
        botaoFrequencia = new javax.swing.JButton();
        botaoFinanceiro = new javax.swing.JButton();
        botaoMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAniversariantes = new javax.swing.JTable();
        planodefundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuGerente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        menuGerente.add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        botaoBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoBackup.png"))); // NOI18N
        botaoBackup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverBackup.png"))); // NOI18N
        botaoBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBackupActionPerformed(evt);
            }
        });
        menuGerente.add(botaoBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 360, 50));

        botaoImprimirExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoImprimir.png"))); // NOI18N
        botaoImprimirExportar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverImprimir.png"))); // NOI18N
        botaoImprimirExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirExportarActionPerformed(evt);
            }
        });
        menuGerente.add(botaoImprimirExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 360, 50));

        botaoFinanceiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoFinanceiro.png"))); // NOI18N
        botaoFinanceiro1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverFinanceiro.png"))); // NOI18N
        botaoFinanceiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinanceiro1ActionPerformed(evt);
            }
        });
        menuGerente.add(botaoFinanceiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 360, 50));

        botaoServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoServicos.png"))); // NOI18N
        botaoServicos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverServicos.png"))); // NOI18N
        botaoServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicosActionPerformed(evt);
            }
        });
        menuGerente.add(botaoServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 360, 50));

        botaoTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoTurmas.png"))); // NOI18N
        botaoTurmas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverTurmas.png"))); // NOI18N
        botaoTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTurmasActionPerformed(evt);
            }
        });
        menuGerente.add(botaoTurmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 360, 50));

        botaoAlunos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoAlunos.png"))); // NOI18N
        botaoAlunos1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverAlunos.png"))); // NOI18N
        botaoAlunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunos1ActionPerformed(evt);
            }
        });
        menuGerente.add(botaoAlunos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 360, 50));

        botaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoProdutos.png"))); // NOI18N
        botaoProdutos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverProdutos.png"))); // NOI18N
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });
        menuGerente.add(botaoProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 360, 50));

        botaoCaixa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoCaixa.png"))); // NOI18N
        botaoCaixa1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverCaixa.png"))); // NOI18N
        botaoCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixa1ActionPerformed(evt);
            }
        });
        menuGerente.add(botaoCaixa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 360, 50));

        botaoSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoSair.png"))); // NOI18N
        botaoSair1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menufuncionario/botaoHoverSair.png"))); // NOI18N
        botaoSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSair1ActionPerformed(evt);
            }
        });
        menuGerente.add(botaoSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 880, 270, 52));

        planodefundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/menu-principal-funcionárioFundo.png"))); // NOI18N
        menuGerente.add(planodefundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1020));

        getContentPane().add(menuGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 1030));

        botaoFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialgerente/funcionarios.png"))); // NOI18N
        botaoFuncionarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialgerente/funcionarioshover.png"))); // NOI18N
        botaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 168, 203));

        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 940, 90, 25));

        botaoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/caixaprincipal.png"))); // NOI18N
        botaoCaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/caixaHoverPrincipal.png"))); // NOI18N
        botaoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 90, 168, 203));

        animaçãoRehabiliter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rehab.gif"))); // NOI18N
        getContentPane().add(animaçãoRehabiliter, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 810, 420, 190));

        botaoAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/alunosprincipal.png"))); // NOI18N
        botaoAlunos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/alunosHoverprincipal.png"))); // NOI18N
        botaoAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 168, 203));

        botaoFrequencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/frequenciaprincipal.png"))); // NOI18N
        botaoFrequencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/frequenciaHoverprincipal.png"))); // NOI18N
        botaoFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFrequenciaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFrequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 90, 168, 203));

        botaoFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/financeiroprincipal.png"))); // NOI18N
        botaoFinanceiro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/financeiroHoverprincipal.png"))); // NOI18N
        botaoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 90, 168, 203));

        botaoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/menuprincipal.png"))); // NOI18N
        botaoMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telainicialfuncionario/menuHoverPrincipal.png"))); // NOI18N
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 110, 70));

        tabelaAniversariantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aniversariante do Mês", "Turma", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAniversariantes.setAutoscrolls(false);
        tabelaAniversariantes.setRowSelectionAllowed(false);
        tabelaAniversariantes.getTableHeader().setResizingAllowed(false);
        this.defineRenderers();
        tabelaAniversariantes.getTableHeader().setReorderingAllowed(false);
        tabelaAniversariantes.setBackground(new Color(0,134, 190));
        tabelaAniversariantes.setForeground(Color.WHITE);
        tabelaAniversariantes.setShowGrid(false);
        jScrollPane1.setViewportView(tabelaAniversariantes);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0,0), 1, true));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 350, 316, 180));

        planodefundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/tela-inicial-gerentefundo.jpg"))); // NOI18N
        getContentPane().add(planodefundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        try {
            controller.sairTela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoginGerente jump = new LoginGerente();
        jump.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunosActionPerformed
        // TODO add your handling code here:
        try {
            if(controller.permissaoDeAcessoATela()){
                telaAlunos.setModal(true);
                telaAlunos.setLocationRelativeTo(null);
                telaAlunos.setVisible(true);   
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoAlunosActionPerformed

    private void botaoFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFrequenciaActionPerformed
        // TODO add your handling code here:
        try {
            if(controller.permissaoDeAcessoATela()){
                telaTurmasFrequencia.setModal(true);
                telaTurmasFrequencia.setLocationRelativeTo(null);
                telaTurmasFrequencia.setVisible(true);
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoFrequenciaActionPerformed

    private void botaoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinanceiroActionPerformed
        // TODO add your handling code here:
        Financeiro abrir=new Financeiro();
        try {
            if(controller.permissaoDeAcessoATela()){
                abrir.setVisible(true);
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoFinanceiroActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(true);
    }//GEN-LAST:event_botaoMenuActionPerformed

    private void botaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFuncionariosActionPerformed
        Funcionarios telaFuncionarios = new Funcionarios();
        try {
            if(controller.permissaoDeAcessoATela()){
                telaFuncionarios.setVisible(true);
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoFuncionariosActionPerformed

    private void botaoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixaActionPerformed
        // TODO add your handling code here:
        Caixa abrir= new Caixa();
        try {
            if(controller.permissaoDeAcessoATela()){
                abrir.setVisible(true);
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoCaixaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            controller.inicializarTabela();
            controller.setarPlanos();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        menuGerente.setVisible(false);

    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoImprimirExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirExportarActionPerformed
        // TODO add your handling code here:
        ImprimirExportarGerente abrir= new ImprimirExportarGerente();
        abrir.setVisible(true);
        menuGerente.setVisible(false);
    }//GEN-LAST:event_botaoImprimirExportarActionPerformed

    private void botaoFinanceiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinanceiro1ActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(false);
        Financeiro abrir = new Financeiro();
        abrir.setVisible(true);
    }//GEN-LAST:event_botaoFinanceiro1ActionPerformed

    private void botaoServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicosActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(false);
        try {
            if(controller.permissaoDeAcessoATela()){
                telaServicos.setModal(true);
                telaServicos.setLocationRelativeTo(null);
                telaServicos.setVisible(true);
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoServicosActionPerformed

    private void botaoTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTurmasActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(false);
        try{
            if(controller.permissaoDeAcessoATela()){
                telaTurmas.setModal(true);
                telaTurmas.setLocationRelativeTo(null);
                telaTurmas.setVisible(true);   
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoTurmasActionPerformed

    private void botaoAlunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunos1ActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(false);
        try {
            if(controller.permissaoDeAcessoATela()){
                telaAlunos.setModal(true);
                telaAlunos.setLocationRelativeTo(null);
                telaAlunos.setVisible(true);   
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoAlunos1ActionPerformed

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
        // TODO add your handling code here:
        menuGerente.setVisible(false);
        try {
            if(controller.permissaoDeAcessoATela()){
                telaProdutos.setModal(true);
                telaProdutos.setLocationRelativeTo(null);
                telaProdutos.setVisible(true);   
            }
            else{this.exibeMensagem("Acesso Negado");}
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicialGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoProdutosActionPerformed

    private void botaoCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixa1ActionPerformed
        // TODO add your handling code here:
        Caixa abrir= new Caixa();
        abrir.setVisible(true);
        menuGerente.setVisible(false);
    }//GEN-LAST:event_botaoCaixa1ActionPerformed

    private void botaoSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSair1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_botaoSair1ActionPerformed

    private void botaoBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBackupActionPerformed
        // TODO add your handling code here:    
        BackupView abrir= new BackupView();
        abrir.setVisible(true);
        menuGerente.setVisible(false);
        
    }//GEN-LAST:event_botaoBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialGerenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialGerenteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animaçãoRehabiliter;
    private javax.swing.JButton botaoAlunos;
    private javax.swing.JButton botaoAlunos1;
    private javax.swing.JButton botaoBackup;
    private javax.swing.JButton botaoCaixa;
    private javax.swing.JButton botaoCaixa1;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoFinanceiro;
    private javax.swing.JButton botaoFinanceiro1;
    private javax.swing.JButton botaoFrequencia;
    private javax.swing.JButton botaoFuncionarios;
    private javax.swing.JButton botaoImprimirExportar;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSair1;
    private javax.swing.JButton botaoServicos;
    private javax.swing.JButton botaoTurmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuGerente;
    private javax.swing.JLabel planodefundo;
    private javax.swing.JLabel planodefundo1;
    private javax.swing.JTable tabelaAniversariantes;
    // End of variables declaration//GEN-END:variables
    
    private void defineRenderers() {
    DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
    rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
    DefaultTableCellHeaderRenderer headerCentro = new DefaultTableCellHeaderRenderer();
    headerCentro.setHorizontalAlignment(SwingConstants.CENTER);
    DefaultTableCellRenderer rendererDireita = new DefaultTableCellRenderer();
    rendererDireita.setHorizontalAlignment(SwingConstants.RIGHT);
    DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();
    rendererEsquerda.setHorizontalAlignment(SwingConstants.LEFT);

    JTableHeader header = tabelaAniversariantes.getTableHeader(); 
    header.setPreferredSize(new Dimension(0, 35)); 
    TableColumnModel modeloDaColuna = tabelaAniversariantes.getColumnModel();

    modeloDaColuna.getColumn(0).setCellRenderer(rendererCentro);
    modeloDaColuna.getColumn(1).setCellRenderer(rendererCentro);
    modeloDaColuna.getColumn(2).setCellRenderer(rendererCentro);

    DefaultTableCellRenderer defaultheader = (DefaultTableCellRenderer) tabelaAniversariantes.getTableHeader().getDefaultRenderer();
    defaultheader.setHorizontalAlignment(SwingConstants.CENTER);

    modeloDaColuna.getColumn(0).setMaxWidth(145);
    modeloDaColuna.getColumn(1).setMaxWidth(90);
    modeloDaColuna.getColumn(2).setMaxWidth(95);

    }
    
    public void exibeMensagem(String mensagem) {
      JOptionPane.showMessageDialog(null, mensagem);
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getTabelaAniversariantes() {
        return tabelaAniversariantes;
    }
    
}
