/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Paineis;

import Controller.CaixaController;
import Controller.auxiliar.JMoneyField;
import View.Caixa;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Mayro
 */
public class CaixaRelatorio extends javax.swing.JDialog {
    private final Caixa view;
    private final CaixaController controller;
    /**
     * Creates new form CaixaRelatorio
     */
    public CaixaRelatorio(java.awt.Frame parent, boolean modal, Caixa view) {
        super(parent, modal);
        initComponents();
        
        this.view = view;
        this.controller = new CaixaController(view, view.getPainelSaldoInicial(), this);
        
        botaoFechar.setBackground(new Color(0,0,0,0));
        this.setBackground(new Color(0,0,0,160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoSaldoInicial = new JMoneyField();
        jLabel7 = new javax.swing.JLabel();
        campoSaldoAtual = new JMoneyField();
        jLabel8 = new javax.swing.JLabel();
        campoVendas = new JMoneyField();
        jLabel9 = new javax.swing.JLabel();
        campoPlanos = new JMoneyField();
        jLabel10 = new javax.swing.JLabel();
        campoDiferencial = new JMoneyField();
        jLabel11 = new javax.swing.JLabel();
        campoArrecadacao = new JMoneyField();
        jLabel12 = new javax.swing.JLabel();
        campoDinheiro = new JMoneyField();
        jLabel13 = new javax.swing.JLabel();
        campoCartao = new JMoneyField();
        botaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(116, 174, 159));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RELATÓRIO DE USO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SALDO INICIAL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        campoSaldoInicial.setEditable(false);
        campoSaldoInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALDO ATUAL CAIXA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 100, -1, 30));

        campoSaldoAtual.setEditable(false);
        campoSaldoAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoSaldoAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VENDAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 30));

        campoVendas.setEditable(false);
        campoVendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PLANOS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 30));

        campoPlanos.setEditable(false);
        campoPlanos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 180, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DIFERENCIAL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 30));

        campoDiferencial.setEditable(false);
        campoDiferencial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoDiferencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ARRECADADO TOTAL");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 180, -1, 30));

        campoArrecadacao.setEditable(false);
        campoArrecadacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoArrecadacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DINHEIRO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 30));

        campoDinheiro.setEditable(false);
        campoDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CARTÃO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 30));

        campoCartao.setEditable(false);
        campoCartao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(campoCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 180, 40));

        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensparaseremtrocadas/btnFecharPeq.png"))); // NOI18N
        botaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 375, 500, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();
        view.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame();
                
                CaixaRelatorio dialog = new CaixaRelatorio(frame, true, new Caixa(frame, true));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoFecharConf;
    private javax.swing.JButton botaoFecharConf1;
    private javax.swing.JTextField campoArrecadacao;
    private javax.swing.JTextField campoCartao;
    private javax.swing.JTextField campoDiferencial;
    private javax.swing.JTextField campoDinheiro;
    private javax.swing.JTextField campoPlanos;
    private javax.swing.JTextField campoSaldoAtual;
    private javax.swing.JTextField campoSaldoInicial;
    private javax.swing.JTextField campoVendas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoArrecadacao() {
        return campoArrecadacao;
    }

    public JTextField getCampoCartao() {
        return campoCartao;
    }

    public JTextField getCampoDiferencial() {
        return campoDiferencial;
    }

    public JTextField getCampoDinheiro() {
        return campoDinheiro;
    }

    public JTextField getCampoPlanos() {
        return campoPlanos;
    }

    public JTextField getCampoSaldoAtual() {
        return campoSaldoAtual;
    }

    public JTextField getCampoSaldoInicial() {
        return campoSaldoInicial;
    }

    public JTextField getCampoVendas() {
        return campoVendas;
    }
    

}
