/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Paineis;

import Controller.Paineis.FuncionariosDetalhesController;
import Controller.auxiliar.JMoneyField;
import View.Funcionarios;
import com.toedter.calendar.JDateChooser;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mayro
 */
public class FuncionariosDetalhes extends javax.swing.JDialog {
    private final FuncionariosDetalhesController controller;
    private Vector <ButtonGroup> grupoRadios = new Vector<ButtonGroup>();
    private Vector <JCheckBox> grupoAlteracoes = new Vector<JCheckBox>();
    /**
     * Creates new form FuncionariosDetalhes
     */
    public FuncionariosDetalhes(Funcionarios funcionarios, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new FuncionariosDetalhesController(funcionarios, this);
        
        this.grupoBotoes();
        this.configsIniciais();
        this.actionListenerRadios();
        this.actionListenerPaineis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botaoSair = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoConcluir = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        painelDados = new javax.swing.JPanel();
        checkAlteracoesDados = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JFormattedTextField();
        campoNascimento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        comboCargos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        painelNovoTipo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        campoNovoTipo = new javax.swing.JTextField();
        campoSalario = new JMoneyField();
        jLabel10 = new javax.swing.JLabel();
        painelContato = new javax.swing.JPanel();
        checkAlteracoesContatos = new javax.swing.JCheckBox();
        campoEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        campoCelular = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        checkExibirSenha = new javax.swing.JCheckBox();
        painelPermissoes = new javax.swing.JPanel();
        checkAlteracoesPermissoes = new javax.swing.JCheckBox();
        radioAlunosNao = new javax.swing.JRadioButton();
        radioAlunosSim = new javax.swing.JRadioButton();
        radioTurmasSim = new javax.swing.JRadioButton();
        radioTurmasNao = new javax.swing.JRadioButton();
        radioProdutosNao = new javax.swing.JRadioButton();
        radioProdutosSim = new javax.swing.JRadioButton();
        radioServicosSim = new javax.swing.JRadioButton();
        radioServicosNao = new javax.swing.JRadioButton();
        radioFinanceiroNao = new javax.swing.JRadioButton();
        radioFinanceiroSim = new javax.swing.JRadioButton();
        radioImprimirNao = new javax.swing.JRadioButton();
        radioImprimirSim = new javax.swing.JRadioButton();
        radioBackupSim = new javax.swing.JRadioButton();
        radioBackupNao = new javax.swing.JRadioButton();
        radioCaixaNao = new javax.swing.JRadioButton();
        radioCaixaSim = new javax.swing.JRadioButton();
        radioReposicoesNao = new javax.swing.JRadioButton();
        radioReposicoesSim = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoSair.setBackground(new java.awt.Color(255, 51, 51));
        botaoSair.setText("X");
        botaoSair.setMaximumSize(new java.awt.Dimension(40, 25));
        botaoSair.setMinimumSize(new java.awt.Dimension(40, 25));
        botaoSair.setPreferredSize(new java.awt.Dimension(40, 25));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        jPanel2.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 25));

        botaoEditar.setBackground(new java.awt.Color(0, 204, 204));
        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 140, 50));

        botaoConcluir.setBackground(new java.awt.Color(0, 204, 0));
        botaoConcluir.setText("Concluir");
        botaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluirActionPerformed(evt);
            }
        });
        jPanel2.add(botaoConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 140, 50));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        painelDados.setBackground(new java.awt.Color(157, 197, 188));
        painelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkAlteracoesDados.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        checkAlteracoesDados.setText("Há alterações não salvas");
        painelDados.add(checkAlteracoesDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(11, 13, 138));
        jLabel6.setText("Nascimento");
        painelDados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 13, 138));
        jLabel5.setText("Nome");
        painelDados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        painelDados.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 370, 30));

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDados.add(campoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));
        painelDados.add(campoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(11, 13, 138));
        jLabel7.setText("Cargo");
        painelDados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        comboCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Nenhum]" }));
        comboCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboCargosMouseClicked(evt);
            }
        });
        comboCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargosActionPerformed(evt);
            }
        });
        painelDados.add(comboCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(11, 13, 138));
        jLabel8.setText("CPF");
        painelDados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        painelNovoTipo.setBackground(new java.awt.Color(157, 197, 188));
        painelNovoTipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(11, 13, 138));
        jLabel9.setText("Novo Tipo");
        painelNovoTipo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        campoNovoTipo.setText("Outro");
        campoNovoTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNovoTipoMouseClicked(evt);
            }
        });
        painelNovoTipo.add(campoNovoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, 30));

        painelDados.add(painelNovoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 60));
        painelDados.add(campoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 13, 138));
        jLabel10.setText("Remuneração");
        painelDados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jTabbedPane2.addTab("Dados", painelDados);

        painelContato.setBackground(new java.awt.Color(157, 197, 188));
        painelContato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkAlteracoesContatos.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        checkAlteracoesContatos.setText("Há alterações não salvas");
        painelContato.add(checkAlteracoesContatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));
        painelContato.add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 370, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(11, 13, 138));
        jLabel13.setText("Senha");
        painelContato.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelContato.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 30));

        try {
            campoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelContato.add(campoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(11, 13, 138));
        jLabel11.setText("Celular");
        painelContato.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(11, 13, 138));
        jLabel12.setText("Telefone");
        painelContato.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        painelContato.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(11, 13, 138));
        jLabel14.setText("E-mail");
        painelContato.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        checkExibirSenha.setText("Exibir Senha");
        checkExibirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkExibirSenhaActionPerformed(evt);
            }
        });
        painelContato.add(checkExibirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 30));

        jTabbedPane2.addTab("Contato", painelContato);

        painelPermissoes.setBackground(new java.awt.Color(157, 197, 188));
        painelPermissoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkAlteracoesPermissoes.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        checkAlteracoesPermissoes.setText("Há alterações não salvas");
        painelPermissoes.add(checkAlteracoesPermissoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        radioAlunosNao.setSelected(true);
        painelPermissoes.add(radioAlunosNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));
        painelPermissoes.add(radioAlunosSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        painelPermissoes.add(radioTurmasSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        radioTurmasNao.setSelected(true);
        painelPermissoes.add(radioTurmasNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        radioProdutosNao.setSelected(true);
        painelPermissoes.add(radioProdutosNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));
        painelPermissoes.add(radioProdutosSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));
        painelPermissoes.add(radioServicosSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        radioServicosNao.setSelected(true);
        painelPermissoes.add(radioServicosNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        radioFinanceiroNao.setSelected(true);
        painelPermissoes.add(radioFinanceiroNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));
        painelPermissoes.add(radioFinanceiroSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        radioImprimirNao.setSelected(true);
        painelPermissoes.add(radioImprimirNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        painelPermissoes.add(radioImprimirSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));
        painelPermissoes.add(radioBackupSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        radioBackupNao.setSelected(true);
        painelPermissoes.add(radioBackupNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        radioCaixaNao.setSelected(true);
        painelPermissoes.add(radioCaixaNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));
        painelPermissoes.add(radioCaixaSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        radioReposicoesNao.setSelected(true);
        painelPermissoes.add(radioReposicoesNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));
        painelPermissoes.add(radioReposicoesSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(11, 13, 138));
        jLabel15.setText("NÃO");
        painelPermissoes.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 25, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(11, 13, 138));
        jLabel16.setText("Reposição");
        painelPermissoes.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 445, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(11, 13, 138));
        jLabel17.setText("SIM");
        painelPermissoes.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 25, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(11, 13, 138));
        jLabel18.setText("Alunos");
        painelPermissoes.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(11, 13, 138));
        jLabel19.setText("Turmas");
        painelPermissoes.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(11, 13, 138));
        jLabel20.setText("Produtos");
        painelPermissoes.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 145, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(11, 13, 138));
        jLabel21.setText("Serviços");
        painelPermissoes.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 195, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(11, 13, 138));
        jLabel22.setText("Financeiro");
        painelPermissoes.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 245, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(11, 13, 138));
        jLabel23.setText("Imp/Exp");
        painelPermissoes.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(11, 13, 138));
        jLabel24.setText("Backup");
        painelPermissoes.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 345, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(11, 13, 138));
        jLabel25.setText("Caixa");
        painelPermissoes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 395, -1, -1));

        jTabbedPane2.addTab("Permissões", painelPermissoes);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        controller.sairTela();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        trocaBotoes(true);
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConcluirActionPerformed
        controller.editarFuncionario();
    }//GEN-LAST:event_botaoConcluirActionPerformed

    private void comboCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargosActionPerformed
        if(comboCargos.getSelectedIndex()==0){
            painelNovoTipo.setVisible(true);
        }
        else{
            painelNovoTipo.setVisible(false);
        }
    }//GEN-LAST:event_comboCargosActionPerformed

    private void comboCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCargosMouseClicked
        painelNovoCargo(false);
    }//GEN-LAST:event_comboCargosMouseClicked

    private void campoNovoTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNovoTipoMouseClicked
        painelNovoCargo(true);
    }//GEN-LAST:event_campoNovoTipoMouseClicked

    private void checkExibirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkExibirSenhaActionPerformed
        if(checkExibirSenha.isSelected()){
            campoSenha.setEchoChar('\u0000');
        }else{
            campoSenha.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_checkExibirSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionariosDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionariosDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionariosDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame();
                FuncionariosDetalhes dialog = new FuncionariosDetalhes(new Funcionarios(frame,true), frame, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConcluir;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JTextField campoEmail;
    private com.toedter.calendar.JDateChooser campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNovoTipo;
    private javax.swing.JFormattedTextField campoSalario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JCheckBox checkAlteracoesContatos;
    private javax.swing.JCheckBox checkAlteracoesDados;
    private javax.swing.JCheckBox checkAlteracoesPermissoes;
    private javax.swing.JCheckBox checkExibirSenha;
    private javax.swing.JComboBox<String> comboCargos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel painelContato;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelNovoTipo;
    private javax.swing.JPanel painelPermissoes;
    private javax.swing.JRadioButton radioAlunosNao;
    private javax.swing.JRadioButton radioAlunosSim;
    private javax.swing.JRadioButton radioBackupNao;
    private javax.swing.JRadioButton radioBackupSim;
    private javax.swing.JRadioButton radioCaixaNao;
    private javax.swing.JRadioButton radioCaixaSim;
    private javax.swing.JRadioButton radioFinanceiroNao;
    private javax.swing.JRadioButton radioFinanceiroSim;
    private javax.swing.JRadioButton radioImprimirNao;
    private javax.swing.JRadioButton radioImprimirSim;
    private javax.swing.JRadioButton radioProdutosNao;
    private javax.swing.JRadioButton radioProdutosSim;
    private javax.swing.JRadioButton radioReposicoesNao;
    private javax.swing.JRadioButton radioReposicoesSim;
    private javax.swing.JRadioButton radioServicosNao;
    private javax.swing.JRadioButton radioServicosSim;
    private javax.swing.JRadioButton radioTurmasNao;
    private javax.swing.JRadioButton radioTurmasSim;
    // End of variables declaration//GEN-END:variables
    public Vector<ButtonGroup> getGrupoRadios() {
        return grupoRadios;
    }

    public JFormattedTextField getCampoCPF() {
        return campoCPF;
    }

    public JFormattedTextField getCampoCelular() {
        return campoCelular;
    }

    public JTextField getCampoEmail() {
        return campoEmail;
    }

    public JDateChooser getCampoNascimento() {
        return campoNascimento;
    }

    public JTextField getCampoNome() {
        return campoNome;
    }

    public JTextField getCampoNovoTipo() {
        return campoNovoTipo;
    }

    public JFormattedTextField getCampoSalario() {
        return campoSalario;
    }

    public JPasswordField getCampoSenha() {
        return campoSenha;
    }

    public JFormattedTextField getCampoTelefone() {
        return campoTelefone;
    }

    public JComboBox<String> getComboCargos() {
        return comboCargos;
    }
    
    public Vector<JCheckBox> getGrupoAlteracoes() {
        return grupoAlteracoes;
    }
    
    public JCheckBox getCheckExibirSenha() {
        return checkExibirSenha;
    }
    

    private void grupoBotoes(){
        //Alunos
        ButtonGroup grupo1 = new ButtonGroup();
        radioAlunosSim.setActionCommand("Sim");
        radioAlunosNao.setActionCommand("Não");
        grupo1.add(radioAlunosSim);
        grupo1.add(radioAlunosNao);
        this.grupoRadios.add(grupo1);
        
        //Turmas
        ButtonGroup grupo2 = new ButtonGroup();
        radioTurmasSim.setActionCommand("Sim");
        radioTurmasNao.setActionCommand("Não");
        grupo2.add(radioTurmasSim);
        grupo2.add(radioTurmasNao);
        this.grupoRadios.add(grupo2);
        
        //Produtos
        ButtonGroup grupo3 = new ButtonGroup();
        radioProdutosSim.setActionCommand("Sim");
        radioProdutosNao.setActionCommand("Não");
        grupo3.add(radioProdutosSim);
        grupo3.add(radioProdutosNao);
        this.grupoRadios.add(grupo3);
        
        //Serviços
        ButtonGroup grupo4 = new ButtonGroup();
        radioServicosSim.setActionCommand("Sim");
        radioServicosNao.setActionCommand("Não");
        grupo4.add(radioServicosSim);
        grupo4.add(radioServicosNao);
        this.grupoRadios.add(grupo4);
        
        //Financeiro
        ButtonGroup grupo5 = new ButtonGroup();
        radioFinanceiroSim.setActionCommand("Sim");
        radioFinanceiroNao.setActionCommand("Não");
        grupo5.add(radioFinanceiroSim);
        grupo5.add(radioFinanceiroNao);
        this.grupoRadios.add(grupo5);
        
        //Imprimir
        ButtonGroup grupo6 = new ButtonGroup();
        radioImprimirSim.setActionCommand("Sim");
        radioImprimirNao.setActionCommand("Não");
        grupo6.add(radioImprimirSim);
        grupo6.add(radioImprimirNao);
        this.grupoRadios.add(grupo6);
        
        //Backup
        ButtonGroup grupo7 = new ButtonGroup();
        radioBackupSim.setActionCommand("Sim");
        radioBackupNao.setActionCommand("Não");
        grupo7.add(radioBackupSim);
        grupo7.add(radioBackupNao);
        this.grupoRadios.add(grupo7);
        
        //Caixa
        ButtonGroup grupo8 = new ButtonGroup();
        radioCaixaSim.setActionCommand("Sim");
        radioCaixaNao.setActionCommand("Não");
        grupo8.add(radioCaixaSim);
        grupo8.add(radioCaixaNao);
        this.grupoRadios.add(grupo8);
        
        //Reposições
        ButtonGroup grupo9 = new ButtonGroup();
        radioReposicoesSim.setActionCommand("Sim");
        radioReposicoesNao.setActionCommand("Não");
        grupo9.add(radioReposicoesSim);
        grupo9.add(radioReposicoesNao);
        this.grupoRadios.add(grupo9);
        
        //Grupo Alteracões
        checkAlteracoesDados.setActionCommand("Dados");
        checkAlteracoesContatos.setActionCommand("Contatos");
        checkAlteracoesPermissoes.setActionCommand("Permissões");
        
        grupoAlteracoes.add(checkAlteracoesDados);
        grupoAlteracoes.add(checkAlteracoesContatos);
        grupoAlteracoes.add(checkAlteracoesPermissoes);
    }
    
    private void painelNovoCargo(boolean novoCargo){
        if(!botaoEditar.isVisible()){
            comboCargos.setEnabled(!novoCargo);
            campoNovoTipo.setEnabled(novoCargo);
            if(novoCargo){
                campoNovoTipo.setText("");
            }else{
                campoNovoTipo.setText("Outro");
            }
        }
        
    }
    
    public void trocaBotoes(boolean editar){
        botaoEditar.setVisible(!editar);
        botaoConcluir.setVisible(editar);
        enableCampos(editar);
    }
    
    
    private void configsIniciais(){
        painelNovoTipo.setVisible(false);
        campoNovoTipo.setEnabled(false);
        
        for(JCheckBox caixa : grupoAlteracoes){
            caixa.setEnabled(false);
            caixa.setVisible(false);
        }
        enableCampos(false);
        checkExibirSenha.setSelected(false);
        
    }
    
    private void enableCampos(boolean enable){
        //Dados
        campoNome.setEditable(enable);
        campoCPF.setEditable(enable);
        campoNascimento.setEnabled(enable);
        comboCargos.setEnabled(enable);
        campoNovoTipo.setEditable(enable);
        campoSalario.setEditable(enable);
        
        //Contatos
        campoTelefone.setEditable(enable);
        campoCelular.setEditable(enable);
        campoEmail.setEditable(enable);
        campoSenha.setEditable(enable);
        
        //Permissões
        int linhas;
        for(ButtonGroup grupo : grupoRadios){
            Enumeration <AbstractButton> enu = grupo.getElements();
            while(enu.hasMoreElements()){
                AbstractButton button = enu.nextElement();
                button.setEnabled(enable);
            }
        }
    }
    
    public void alternarRadios(ButtonGroup grupo, boolean yesOption){
        Enumeration <AbstractButton> enu = grupo.getElements();
        while(enu.hasMoreElements()){
                AbstractButton button = enu.nextElement();
                if(button.getActionCommand().equals("Sim")){
                    button.setSelected(yesOption);
                }
        }
    }
    
    public void ativarCheckAlteracao(JCheckBox caixa, boolean visible){
        if(!caixa.isVisible()){
            caixa.setSelected(visible);
            caixa.setVisible(visible);
        }
        else{
            if(!visible){
                caixa.setSelected(visible);
                caixa.setVisible(visible);
            }
        }
    }
    
    private void actionListenerRadios(){
        Enumeration <AbstractButton> enu;
        AbstractButton button;
        
        AbstractAction action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ativarCheckAlteracao(checkAlteracoesPermissoes, true);
            }
        };
        for(ButtonGroup grupo : grupoRadios){
            enu = grupo.getElements();
            while(enu.hasMoreElements()){
                button = enu.nextElement();
                button.addActionListener(action);
            }
        }
    }
    
    private void actionListenerPaineis(){
        Component[] componentsDados = painelDados.getComponents();
        Component[] componentsContato = painelContato.getComponents();
        
        ActionListener action1 = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ativarCheckAlteracao(checkAlteracoesDados, true);
            }
        };
        
        KeyListener key = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                ativarCheckAlteracao(checkAlteracoesDados, true);
            }
            public void keyPressed(KeyEvent e) {}
            public void keyReleased(KeyEvent e) {}
        };
        
        KeyListener key2 = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                ativarCheckAlteracao(checkAlteracoesContatos, true);
            }
            public void keyPressed(KeyEvent e) {}
            public void keyReleased(KeyEvent e) {}
        };
        

        
        for(Component componente:componentsDados){
            if(componente instanceof JTextField){
                ((JTextField) componente).addKeyListener(key);
            }
            if(componente instanceof JComboBox){
                ((JComboBox) componente).addActionListener(action1);
            }
            //JChooserDate
            if(componente instanceof JDateChooser){
                ((JDateChooser)componente).getDateEditor().getUiComponent().addKeyListener(key);
                ((JDateChooser)componente).getCalendarButton().addActionListener(action1);
            }
        }
        
        for(Component componente : componentsContato){
            if(componente instanceof JTextField){
                ((JTextField)componente).addKeyListener(key);
            }
        }

    }
}
